Traceback (most recent call last):
  File "/Users/nataliethurlby/phd/jupyter_books_etc/jekyll-version/phenotype_from_genotype/venv/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/nataliethurlby/phd/jupyter_books_etc/jekyll-version/phenotype_from_genotype/venv/lib/python3.7/site-packages/nbclient/client.py", line 1077, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/nataliethurlby/phd/jupyter_books_etc/jekyll-version/phenotype_from_genotype/venv/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/nataliethurlby/phd/jupyter_books_etc/jekyll-version/phenotype_from_genotype/venv/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/nataliethurlby/phd/jupyter_books_etc/jekyll-version/phenotype_from_genotype/venv/lib/python3.7/site-packages/nbclient/client.py", line 527, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/nataliethurlby/phd/jupyter_books_etc/jekyll-version/phenotype_from_genotype/venv/lib/python3.7/site-packages/nbclient/client.py", line 822, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/nataliethurlby/phd/jupyter_books_etc/jekyll-version/phenotype_from_genotype/venv/lib/python3.7/site-packages/nbclient/client.py", line 730, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
---
render:
  image:
    width: 200px
  figure:
    caption: |
      Funnel chart showing the data selection.
    name: funnel-combine-gxa
---

fig <- plot_ly()
fig <- fig %>%
  add_trace(
  type = "funnel",
  y = as.character(funnel_info$name),
  x = as.integer(funnel_info$num_experiments)
  )
fig <- fig %>%
  layout(yaxis = list(categoryarray = as.character(funnel_info$name)))

display(fig)
------------------

Error in parse(text = x, srcfile = src): <text>:4:15: unexpected symbol
3:   image:
4:     width: 200px
                 ^
Traceback:

ERROR: Error in parse(text = x, srcfile = src): <text>:4:15: unexpected symbol
3:   image:
4:     width: 200px
                 ^


